google_client_id: 1073270019205-7025fshtqil8j9h6101bo6qjk9aoojn4.apps.googleusercontent.com
google_client_secret: 0rdpYDUOWZWlwLTYJVPeY46E

coveralls_repo_token: Ww4VWorYRpi1dJDDxGleMGNz4KJjUJSwO

#for testing:
provider: "google_oauth2"
uid: "113078026318261011396"
name: "Anna Lewis"
oauth_token: ya29.GlujBew2k7GICFo52bv9fgbE2mPIWX095PUV3l2elfpDWcW6AfirowxY2MN2AAeN8xh2tX2G6zYexTLTehWNUvESxUtU-m07VSZJEB-EaA04aYAZbtUZOGv1_Zrl
oauth_expires_at: "2018-04-20 16:23:52 -0600"
refresh_token: "1/wA_kNbH0Zx7pJBBGcISXmkUn_mlM7N7X7v7ej0N6y3Q"
calendar: "me7fhkuj5k21tao766le2plvak@group.calendar.google.com"