google_client_id: 1073270019205-7025fshtqil8j9h6101bo6qjk9aoojn4.apps.googleusercontent.com
google_client_secret: 0rdpYDUOWZWlwLTYJVPeY46E

coveralls_repo_token: Ww4VWorYRpi1dJDDxGleMGNz4KJjUJSwO

#for testing:
provider: "google_oauth2"
uid: "113078026318261011396"
name: "Anna Lewis"
oauth_token: ya29.GlujBXXyo3GJAkx6LV99ccMjHr5QCx_MiKQrQI2B5tbCtTHadiOowoxu_rlm-_a44QfdF-NraMHocsYa5JxpV4LrXwO4mhVAPdDxaZM7xDrorJBDi5goOPkbg170
oauth_expires_at: "2018-04-20 14:50:35 -0600"
refresh_token: "1/93oY8n8s2gQQAz677OPYNyw5ygUJL_fiA5vB08D9QRkBcaTJcHOx2rtexTk8zpED"
calendar: "me7fhkuj5k21tao766le2plvak@group.calendar.google.com"