google_client_id: 1073270019205-7025fshtqil8j9h6101bo6qjk9aoojn4.apps.googleusercontent.com
google_client_secret: 0rdpYDUOWZWlwLTYJVPeY46E

coveralls_repo_token: Ww4VWorYRpi1dJDDxGleMGNz4KJjUJSwO

#for testing:
oauth_token: ya29.GlxvBXD6-Y-breXHvjphPHM5_BsCiviyftMJrawrd63sDndENY3m9VF_zzeDMbA9FQE49hCg4tHurUIHSBQ3ivT7mwFhg12BLhnVOIkcKKrJ-Q2snYYnXXcS8YSQMw
uid: "106325757403341027427"
calendar: 7i483dldd3apdnkk2nnbg63jno@group.calendar.google.com
refresh_token: 